version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/web/Dockerfile
    image: millm_wt
    command: /start
    volumes:
      - .:/app
    ports:
      - 8130:8000
    stdin_open: true
    tty: true
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=millm
      - POSTGRES_USER=millm
      - POSTGRES_PASSWORD=millm

volumes:
  postgres_data:

